# Jason R Laurich

# August 16th, 2026

# This is a master script that sources and runs all other scripts in the analytical pipeline.
# All main text and supporting analyses and figures can be generated by running this script. 

# Section 1: model fitting—experimentally evolved C. reinhardtii -------------------

# Note that these scripts are all commented out due to their computational burden 
# and the time it takes to run to fit hundreds of Bayesian models in R2jags

# To run these scripts in the master script, simply remove the '#' before their source commands

# message("Running 01_light.R") 
# source("scripts-R/01_light.R") # Light: growth rate estimation and Monod curve fitting

# message("Running 02_nitrogen.R")
# source("scripts-R/02_nitrogen.R") # Nitrogen: growth rate estimation and Monod curve fitting

# message("Running 03_phosphorus.R")
# source("scripts-R/03_phosphorus.R") # Phosphorus: growth rate estimation and Monod curve fitting

# message("Running 04_salt.R")
# source("scripts-R/04_salt.R") # Salt: growth rate estimation and salt tolerance curve fitting

# message("Running 05_temperature.R")
# source("scripts-R/05_temperature.R") # Temperature: growth rate estimation and thermal performance curve fitting

# Section 2: analyses—experimentally evolved C. reinhardtii populations -------------------

message("Running 06_data_compilation.R")
source("scripts-R/06_data_compilation.R") # Compile the summary data table

message("Running 07_conceptual_figure.R")
source("scripts-R/07_conceptual_figure.R") # Build and output the conceptual figure (1)

message("Running 08_intra-gradient_trade-offs.R")
source("scripts-R/08_intra-gradient_trade-offs.R") # single niche axis comparisons, figures 2 and s3

message("Running 09_inter-gradient_trade-offs.R")
source("scripts-R/09_inter-gradient_trade-offs.R") # cross-axis comparisons, figures 3 and s4

message("Running 10_secondary_trait_trade-offs.R")
source("scripts-R/10_secondary_trait_trade-offs.R") # comparisons with stoichiometry, pigmentation and biovalume, figure s7

message("Running 11_sensitivity_analysis.R")
source("scripts-R/11_sensitivity_analysis.R") # analysis of the sensitivity of Pareto fronts to threshold cutoff for data retention. Figure s2

message("Running 12_evol_effects_modelling.R")
source("scripts-R/12_evol_effects_modelling.R") # assesses effects of evolutionary treatment and ancestry on univariate trait changes

message("Running 13_PCA_RDA.R")
source("scripts-R/13_PCA_RDA.R") # PCA and RDA, figures s5 and s6

message("Running 20_model_fitting_schema.R")
source("scripts-R/20_model_fitting_schema.R") # schematic representation of model fitting appraoch, figure s1

# Section 3: model fitting on phytoplankton synthesis data ----------------

# As with microevolutionary data, these are commented out to reduce computational time.
# If fitting objects from scratch, the temperature models (17_synthesis_temperature.R) must be fit first. 

# message("Running 17_synthesis_temperature.R")
# source("scripts-R/17_synthesis_temperature.R") # Temperature: growth rate estimation and thermal performance curve fitting

# message("Running 14_synthesis_light.R") 
# source("scripts-R/14_synthesis_light.R") # Light: growth rate estimation and Monod curve fitting

# message("Running 15_synthesis_nitrogen.R")
# source("scripts-R/15_synthesis_nitrogen.R") # Nitrogen: growth rate estimation and Monod curve fitting

# message("Running 16_synthesis_phosphorus.R")
# source("scripts-R/16_synthesis_phosphorus.R") # Phosphorus: growth rate estimation and Monod curve fitting

# Section 4: synthesis data set -------------------

message("Running 18_synthesis_pareto.R")
source("scripts-R/18_synthesis_pareto.R") # Pareto front analysis across phytoplankton. Figures 4 and s8

message("Running 19_summary_fig.R")
source("scripts-R/19_summary_fig.R") # Creates the summary figure (5)
